### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by rafaelstz** [tiagosampaio/ApiPlus#1]
I already have this problem before, this bug is in N98 Magerun.
https://github.com/AOEpeople/MageTestStand/issues/8
https://github.com/netz98/n98-magerun/issues/722

The solution is to change to **magento-mirror-1.9.0.1**.
I already fix in this PR: https://github.com/tiagosampaio/ApiPlus/pull/2

**Comment by rafaelstz** [comment]
Still persist :disappointed: 
![image](https://cloud.githubusercontent.com/assets/610598/19203969/9811ebea-8cb0-11e6-8e17-520412e21ef6.png)

**Comment by tiagosampaio** [comment]
Hi Rafael,

Thank you so much for the information. I already rewrote the build script to use a simpler build process rather than using AOEpeople build script. I'm still using N98 Magerun and it seems to work perfectly for versions CE 1.9 and CE 1.8 and their subversions and 1.7.0.2.

The build script is working properly now.

Thanks,

\- Tiago
